site_name: 'ğŸ«: `clsprop`: Just like @property but for classes ğŸ«'

theme:
  name: material

  palette:
    primary:
      'indigo'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
