[tool.poetry]
name = "clsprop"
version = "1.3.0"
description = "ğŸ« Just like @property but for classes ğŸ«"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rec/clsprop"
homepage = "https://github.com/rec/clsprop"
documentation = "https://rec.github.io/clsprop"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pytest = "*"
mypy = "*"


[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
strict = true
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
