[tool.poetry]
name = "clsprop"
version = "1.2.1"
description = "ğŸ« Just like @property but for classes ğŸ«"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rec/clsprop"
homepage = "https://github.com/rec/clsprop"
documentation = "https://rec.github.io/clsprop"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.group.dev.dependencies]
flake8 = "*"
pytest = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
